version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 8.8.8.8
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "192.168.1.104:53:53/tcp"
      - "192.168.1.104:53:53/udp"
      - "192.168.1.104:67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "192.168.1.104:80:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: Jakiro
      FTLCONF_LOCAL_IPV4: '192.168.1.104'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
